<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlyDoom.Connectome\FlyDoom.Connectome.csproj" />
    <ProjectReference Include="..\FlyDoom.Core\FlyDoom.Core.csproj" />
    <ProjectReference Include="..\FlyDoom.Doom\FlyDoom.Doom.csproj" />
    <ProjectReference Include="..\FlyDoom.Learning\FlyDoom.Learning.csproj" />
    <ProjectReference Include="..\FlyDoom.Neural\FlyDoom.Neural.csproj" />
    <ProjectReference Include="..\FlyDoom.Vision\FlyDoom.Vision.csproj" />
  </ItemGroup>

</Project>
