namespace FlyDoom.Vision.Stimulation;

/// <summary>
/// Describes the neural input generated by one visual stimulus.
/// </summary>
public readonly record struct VisualStimulusStatistics(
    int PhotoreceptorCount,
    long AppliedConnectionCount,
    int UniqueTargetCount,
    float MostNegativeInputAmplitudeMv);